TRUNCATE TABLE quiz_attempts, notes, resources, user_lab_progress, lab_steps, quiz_questions, labs, modules RESTART IDENTITY CASCADE;

INSERT INTO modules (name, description, exam_weight) VALUES
('Identites et gouvernance', 'Microsoft Entra ID, groupes, RBAC, politiques et gouvernance Azure.', '15-20%'),
('Stockage Azure', 'Comptes de stockage, blobs, fichiers, securite et lifecycle management.', '15-20%'),
('Machines virtuelles', 'Provisioning, disponibilite, extensions, disques et operations VM.', '20-25%'),
('Reseau virtuel', 'VNets, sous-reseaux, peering, NSG, DNS et connectivite hybride.', '20-25%'),
('Monitoring', 'Azure Monitor, Log Analytics, alertes et diagnostics.', '10-15%'),
('Backup et Recovery', 'Azure Backup, Recovery Services Vault et restauration.', '10-15%'),
('Securite et RBAC', 'Role assignments, least privilege, Defender for Cloud et securite operationnelle.', '15-20%');

INSERT INTO labs (
  module_id, title, slug, objective, prerequisites, difficulty, estimated_minutes,
  azure_services, useful_commands, common_pitfalls, understanding_goals, verification_steps
) VALUES
((SELECT id FROM modules WHERE name = 'Identites et gouvernance'), 'Creer un Resource Group avec tags', 'resource-group-tags',
'Creer un groupe de ressources propre, tague et pret a recevoir les ressources des labs.',
'Azure CLI connecte avec az login, une subscription selectionnee, convention de nommage rg-az104-<usage>.',
'debutant', 25, ARRAY['Resource Groups','Tags'],
'[{"label":"Creer le RG","command":"az group create --name rg-az104-core --location canadacentral --tags env=lab owner=az104 costCenter=training"},{"label":"Lister les tags","command":"az group show --name rg-az104-core --query tags"}]'::jsonb,
ARRAY['Oublier de selectionner la bonne subscription','Utiliser une region differente des ressources prevues','Creer des tags incoherents qui compliquent les rapports de cout'],
ARRAY['Un resource group est un conteneur logique, pas une limite reseau','Les tags aident a gouverner les couts et l ownership','Les ressources heritent rarement automatiquement de tous les tags du RG'],
ARRAY['az group show retourne le RG dans la bonne region','Les tags env, owner et costCenter sont presents','Le portail affiche le meme groupe de ressources']),
((SELECT id FROM modules WHERE name = 'Securite et RBAC'), 'Configurer RBAC sur un Resource Group', 'rbac-resource-group',
'Attribuer un role au scope le plus bas possible et verifier l acces effectif.',
'Un resource group existant et un utilisateur ou groupe Entra ID de test.',
'intermediaire', 40, ARRAY['Azure RBAC','Microsoft Entra ID'],
'[{"label":"Role Reader","command":"az role assignment create --assignee <objectId> --role Reader --resource-group rg-az104-core"},{"label":"Verifier RBAC","command":"az role assignment list --resource-group rg-az104-core --output table"}]'::jsonb,
ARRAY['Assigner Contributor quand Reader suffit','Confondre appId, user principal name et objectId','Tester trop vite avant la propagation RBAC'],
ARRAY['RBAC s applique a un scope precis','Les roles built-in couvrent des permissions differentes','La propagation peut prendre plusieurs minutes'],
ARRAY['L affectation apparait avec le bon principal','Le scope est /resourceGroups/rg-az104-core','Le compte teste ne peut pas modifier si seul Reader est donne']),
((SELECT id FROM modules WHERE name = 'Stockage Azure'), 'Creer un Storage Account securise', 'secure-storage-account',
'Creer un compte de stockage avec options de base securisees et comprendre les decisions de configuration.',
'Resource group de lab, Azure CLI, nom globalement unique en minuscules.',
'intermediaire', 45, ARRAY['Storage Account','Blob Storage','Networking'],
'[{"label":"Creer le storage","command":"az storage account create -g rg-az104-storage -n <uniquestorage> -l canadacentral --sku Standard_LRS --kind StorageV2 --https-only true --min-tls-version TLS1_2"},{"label":"Desactiver public access","command":"az storage account update -g rg-az104-storage -n <uniquestorage> --allow-blob-public-access false"}]'::jsonb,
ARRAY['Nom non unique ou avec caracteres invalides','Laisser l acces public blob active par defaut','Confondre replication LRS, ZRS et GRS'],
ARRAY['Le nom du compte est global dans Azure','HTTPS only et TLS minimisent les risques de transport','La replication influence disponibilite et cout'],
ARRAY['Le compte existe en StorageV2','allowBlobPublicAccess est false','Minimum TLS affiche TLS1_2']),
((SELECT id FROM modules WHERE name = 'Stockage Azure'), 'Creer un File Share Azure', 'azure-file-share',
'Creer un partage Azure Files, configurer un quota et tester le montage ou l acces.',
'Compte de stockage cree, cle de compte disponible, machine locale ou Cloud Shell.',
'debutant', 35, ARRAY['Azure Files','Storage Account'],
'[{"label":"Creer le share","command":"az storage share-rm create --resource-group rg-az104-storage --storage-account <uniquestorage> --name az104share --quota 5"},{"label":"Lister les shares","command":"az storage share-rm list --resource-group rg-az104-storage --storage-account <uniquestorage> -o table"}]'::jsonb,
ARRAY['Melanger commandes data plane et management plane','Oublier le quota','Tenter SMB depuis un reseau qui bloque le port 445'],
ARRAY['Azure Files expose SMB et REST','Le quota limite la capacite facturee potentielle','Le port 445 peut etre bloque hors Azure'],
ARRAY['Le share az104share apparait','Le quota est de 5 GiB','Un fichier test peut etre charge ou cree']),
((SELECT id FROM modules WHERE name = 'Machines virtuelles'), 'Creer une VM Windows', 'windows-vm-basic',
'Deployer une VM Windows avec disque manage, IP publique controlee et acces RDP limite.',
'Resource group, VNet ou creation automatique acceptee, mot de passe respectant la complexite.',
'intermediaire', 55, ARRAY['Virtual Machines','Managed Disks','NSG'],
'[{"label":"Creer VM Windows","command":"az vm create -g rg-az104-vm -n vm-az104-win --image Win2022Datacenter --admin-username azureadmin --admin-password <StrongPassword> --size Standard_B2s"},{"label":"Ouvrir RDP source limitee","command":"az vm open-port -g rg-az104-vm -n vm-az104-win --port 3389 --source-address-prefixes <yourPublicIp>/32"}]'::jsonb,
ARRAY['Ouvrir RDP a Internet entier','Choisir une taille non disponible dans la region','Oublier les couts de disque et IP publique'],
ARRAY['Une VM depend de NIC, disque, NSG et parfois IP publique','RDP doit etre restreint par source','Les tailles influencent cout et capacite'],
ARRAY['La VM est Running','Le port 3389 est limite a ton IP','La connexion RDP reussit avec le compte admin']),
((SELECT id FROM modules WHERE name = 'Machines virtuelles'), 'Creer une VM Linux', 'linux-vm-basic',
'Deployer une VM Linux avec cle SSH et installer un service web simple.',
'Cle SSH locale ou generation automatique, resource group, region choisie.',
'debutant', 45, ARRAY['Virtual Machines','Linux','NSG'],
'[{"label":"Creer VM Linux","command":"az vm create -g rg-az104-vm -n vm-az104-linux --image Ubuntu2204 --admin-username azureuser --generate-ssh-keys --size Standard_B1s"},{"label":"Ouvrir HTTP","command":"az vm open-port -g rg-az104-vm -n vm-az104-linux --port 80"}]'::jsonb,
ARRAY['Perdre la cle privee SSH','Ouvrir SSH a 0.0.0.0/0 inutilement','Oublier de verifier cloud-init ou le package manager'],
ARRAY['SSH utilise une cle publique sur la VM','Les ports entrants passent par le NSG','Une IP publique facilite les tests mais augmente l exposition'],
ARRAY['ssh azureuser@<publicIp> fonctionne','La VM repond a az vm get-instance-view','Le port 80 est accessible apres installation du serveur']),
((SELECT id FROM modules WHERE name = 'Reseau virtuel'), 'Configurer NSG', 'configure-nsg',
'Creer un Network Security Group, ajouter des regles et l associer a un subnet ou une NIC.',
'VNet ou VM existante, connaitre les ports a autoriser et ton IP publique.',
'intermediaire', 45, ARRAY['Network Security Group','Virtual Network'],
'[{"label":"Creer NSG","command":"az network nsg create -g rg-az104-network -n nsg-az104-web"},{"label":"Autoriser HTTP","command":"az network nsg rule create -g rg-az104-network --nsg-name nsg-az104-web -n Allow-HTTP --priority 200 --access Allow --protocol Tcp --direction Inbound --source-address-prefixes Internet --destination-port-ranges 80"}]'::jsonb,
ARRAY['Deux regles avec la meme priorite','Oublier les regles par defaut','Associer le NSG au mauvais subnet'],
ARRAY['Les priorites basses gagnent','NSG peut etre applique a subnet et NIC','Les regles sont stateful'],
ARRAY['La regle apparait avec la priorite 200','Le NSG est associe au bon scope','Le trafic attendu passe et le reste reste bloque']),
((SELECT id FROM modules WHERE name = 'Reseau virtuel'), 'Creer un VNet avec subnet', 'vnet-subnet-basic',
'Creer un reseau virtuel segmente avec sous-reseaux web et data.',
'Plan d adressage simple sans chevauchement, resource group reseau.',
'debutant', 35, ARRAY['Virtual Network','Subnets'],
'[{"label":"Creer VNet","command":"az network vnet create -g rg-az104-network -n vnet-az104 -l canadacentral --address-prefix 10.10.0.0/16 --subnet-name snet-web --subnet-prefix 10.10.1.0/24"},{"label":"Ajouter subnet","command":"az network vnet subnet create -g rg-az104-network --vnet-name vnet-az104 -n snet-data --address-prefixes 10.10.2.0/24"}]'::jsonb,
ARRAY['Chevauchement avec un futur peering ou VPN','Sous-reseau trop petit','Confondre address space VNet et prefix subnet'],
ARRAY['Le VNet fournit l espace IP prive','Les subnets segmentent les workloads','Le CIDR doit anticiper la croissance'],
ARRAY['Le VNet affiche 10.10.0.0/16','Deux subnets existent','Les prefixes ne se chevauchent pas']),
((SELECT id FROM modules WHERE name = 'Reseau virtuel'), 'Peering entre VNets', 'vnet-peering',
'Connecter deux VNets avec peering et valider la connectivite privee.',
'Deux VNets avec espaces non chevauchants, deux VMs de test optionnelles.',
'avance', 55, ARRAY['VNet Peering','Virtual Machines'],
'[{"label":"Peering A vers B","command":"az network vnet peering create -g rg-az104-network -n peer-a-to-b --vnet-name vnet-a --remote-vnet vnet-b --allow-vnet-access"},{"label":"Peering B vers A","command":"az network vnet peering create -g rg-az104-network -n peer-b-to-a --vnet-name vnet-b --remote-vnet vnet-a --allow-vnet-access"}]'::jsonb,
ARRAY['Creer un seul sens de peering','Utiliser des CIDR qui se chevauchent','Supposer que les NSG sont ignores par le peering'],
ARRAY['Le peering doit exister dans les deux directions','Le trafic reste sur backbone Microsoft','NSG et routes continuent de s appliquer'],
ARRAY['Les deux peerings sont Connected','Une VM joint l IP privee de l autre VNet','Les NSG autorisent le trafic teste']),
((SELECT id FROM modules WHERE name = 'Reseau virtuel'), 'Configurer Azure Bastion', 'azure-bastion-basic',
'Deployer Azure Bastion pour administrer des VMs sans IP publique.',
'VNet avec subnet AzureBastionSubnet /26 minimum, VM dans le meme VNet.',
'avance', 60, ARRAY['Azure Bastion','Virtual Network','Virtual Machines'],
'[{"label":"Creer IP publique Bastion","command":"az network public-ip create -g rg-az104-network -n pip-bastion --sku Standard --location canadacentral"},{"label":"Creer Bastion","command":"az network bastion create -g rg-az104-network -n bastion-az104 --public-ip-address pip-bastion --vnet-name vnet-az104 --location canadacentral"}]'::jsonb,
ARRAY['Nommer le subnet autrement que AzureBastionSubnet','Utiliser un subnet trop petit','Garder une IP publique sur la VM malgre Bastion'],
ARRAY['Bastion fournit RDP/SSH via le portail','La VM n a pas besoin d IP publique','Le subnet Bastion a des contraintes de nom et taille'],
ARRAY['Bastion est en etat Succeeded','La VM est joignable via Connect > Bastion','Aucune IP publique n est attachee a la VM cible']),
((SELECT id FROM modules WHERE name = 'Backup et Recovery'), 'Creer une sauvegarde VM', 'vm-backup-create',
'Proteger une VM avec Azure Backup et comprendre vault, policy et point de restauration.',
'VM existante, Recovery Services Vault ou droit de le creer.',
'intermediaire', 50, ARRAY['Azure Backup','Recovery Services Vault','Virtual Machines'],
'[{"label":"Creer vault","command":"az backup vault create -g rg-az104-backup -n rsv-az104 -l canadacentral"},{"label":"Activer backup","command":"az backup protection enable-for-vm -g rg-az104-backup --vault-name rsv-az104 --vm vm-az104-linux --policy-name DefaultPolicy"}]'::jsonb,
ARRAY['Vault dans une region incompatible','Confondre snapshot instantane et point de recovery complet','Ne pas verifier le premier job'],
ARRAY['Le vault stocke les donnees de sauvegarde','Une policy controle frequence et retention','Le premier backup peut prendre du temps'],
ARRAY['La VM apparait comme protected item','Un job de backup est visible','La policy attachee est la bonne']),
((SELECT id FROM modules WHERE name = 'Backup et Recovery'), 'Restaurer une VM', 'vm-restore',
'Lancer une restauration de VM ou de disque et comprendre les options de recovery.',
'VM protegee par Azure Backup avec au moins un recovery point.',
'avance', 65, ARRAY['Azure Backup','Recovery Services Vault','Managed Disks'],
'[{"label":"Lister points","command":"az backup recoverypoint list -g rg-az104-backup --vault-name rsv-az104 --container-name <container> --item-name <item> --backup-management-type AzureIaasVM --workload-type VM"},{"label":"Restaurer disques","command":"az backup restore restore-disks -g rg-az104-backup --vault-name rsv-az104 --container-name <container> --item-name <item> --rp-name <rpName> --storage-account <storage>"}]'::jsonb,
ARRAY['Restaurer dans le mauvais RG','Ne pas preparer le storage account de staging','Confondre restore disks et create new VM'],
ARRAY['Un recovery point represente un etat sauvegarde','La restauration peut creer des disques ou une VM','Le staging storage peut etre requis'],
ARRAY['Le job de restauration se termine sans erreur','Les disques restaures apparaissent','Une VM reconstruite demarre si tu choisis cette option']),
((SELECT id FROM modules WHERE name = 'Monitoring'), 'Creer une alerte Azure Monitor', 'azure-monitor-alert',
'Creer une alerte metrique avec action group pour detecter une anomalie CPU.',
'VM existante, email de notification, droits Monitoring Contributor ou Contributor.',
'debutant', 35, ARRAY['Azure Monitor','Alerts','Action Groups'],
'[{"label":"Action group","command":"az monitor action-group create -g rg-az104-monitor -n ag-az104 --short-name az104 --action email admin az104@example.com"},{"label":"Alerte CPU","command":"az monitor metrics alert create -g rg-az104-monitor -n vm-cpu-high --scopes <vmResourceId> --condition \"avg Percentage CPU > 80\" --window-size 5m --evaluation-frequency 1m --action ag-az104"}]'::jsonb,
ARRAY['Scope de l alerte incorrect','Action group sans recepteur valide','Seuil impossible a declencher pendant un test'],
ARRAY['Une alerte combine condition, scope et action','Les metriques sont differentes des logs','La frequence influence le delai de detection'],
ARRAY['L alerte est enabled','L action group contient un email','Une charge CPU declenche un changement d etat']),
((SELECT id FROM modules WHERE name = 'Monitoring'), 'Log Analytics Workspace', 'log-analytics-workspace',
'Creer un workspace et envoyer des logs pour pouvoir interroger avec KQL.',
'Resource group monitoring, une ressource capable d envoyer des logs.',
'intermediaire', 45, ARRAY['Log Analytics','Azure Monitor','KQL'],
'[{"label":"Creer workspace","command":"az monitor log-analytics workspace create -g rg-az104-monitor -n law-az104 -l canadacentral"},{"label":"Recuperer ID","command":"az monitor log-analytics workspace show -g rg-az104-monitor -n law-az104 --query customerId -o tsv"}]'::jsonb,
ARRAY['Attendre des logs immediatement','Confondre workspace ID et resource ID','Oublier couts d ingestion et retention'],
ARRAY['Log Analytics centralise les journaux','KQL sert a analyser les tables collectees','Retention et ingestion ont un impact cout'],
ARRAY['Le workspace existe','Une table contient des donnees apres configuration','Une requete KQL simple retourne des lignes']),
((SELECT id FROM modules WHERE name = 'Monitoring'), 'Diagnostic settings', 'diagnostic-settings',
'Configurer les diagnostic settings d une ressource vers Log Analytics.',
'Workspace Log Analytics existant et ressource cible comme storage account ou Key Vault.',
'intermediaire', 40, ARRAY['Diagnostic Settings','Log Analytics'],
'[{"label":"Creer diagnostic setting","command":"az monitor diagnostic-settings create --name diag-az104 --resource <resourceId> --workspace <workspaceResourceId> --logs \"[{category:AuditEvent,enabled:true}]\" --metrics \"[{category:AllMetrics,enabled:true}]\""},{"label":"Lister settings","command":"az monitor diagnostic-settings list --resource <resourceId>"}]'::jsonb,
ARRAY['Categories de logs differentes selon la ressource','Utiliser customerId au lieu du resourceId workspace','Tester avant le delai d ingestion'],
ARRAY['Les diagnostic settings routent logs et metriques','Chaque type de ressource a ses categories','Les donnees arrivent avec latence'],
ARRAY['Le setting diag-az104 existe','Les logs cibles sont enabled','Des donnees arrivent dans le workspace']),
((SELECT id FROM modules WHERE name = 'Identites et gouvernance'), 'Managed Identity', 'managed-identity',
'Activer une managed identity sur une VM et lui donner acces a une ressource sans secret.',
'VM existante, ressource cible comme Storage ou Key Vault, droits pour creer role assignment.',
'intermediaire', 45, ARRAY['Managed Identity','Azure RBAC','Virtual Machines'],
'[{"label":"Activer identity","command":"az vm identity assign -g rg-az104-vm -n vm-az104-linux"},{"label":"Assigner role","command":"az role assignment create --assignee <principalId> --role \"Storage Blob Data Reader\" --scope <storageResourceId>"}]'::jsonb,
ARRAY['Utiliser l objectId de la VM au lieu du principalId identity','Donner un role management plane pour un besoin data plane','Oublier la propagation RBAC'],
ARRAY['Managed identity evite de stocker des secrets','System-assigned vit avec la ressource','RBAC controle ce que l identity peut faire'],
ARRAY['principalId est present sur la VM','Le role assignment existe au bon scope','Un token IMDS peut etre obtenu depuis la VM']),
((SELECT id FROM modules WHERE name = 'Securite et RBAC'), 'Key Vault basics', 'key-vault-basics',
'Creer un Key Vault, stocker un secret et configurer un acces minimal.',
'Resource group, droits Key Vault Administrator ou role equivalent, Azure CLI connecte.',
'intermediaire', 45, ARRAY['Key Vault','Secrets','RBAC'],
'[{"label":"Creer vault","command":"az keyvault create -g rg-az104-sec -n <uniqueVaultName> -l canadacentral --enable-rbac-authorization true"},{"label":"Ajouter secret","command":"az keyvault secret set --vault-name <uniqueVaultName> -n demo-secret --value \"ChangeMe123!\""}]'::jsonb,
ARRAY['Nom Key Vault non unique','Confondre access policies et RBAC mode','Mettre de vrais secrets dans les notes ou scripts'],
ARRAY['Key Vault protege secrets, cles et certificats','Le mode RBAC utilise Azure RBAC pour l acces','Les secrets ont versions et metadonnees'],
ARRAY['Le vault existe en RBAC mode','Le secret demo-secret a une version','Un principal autorise peut lire le secret']),
((SELECT id FROM modules WHERE name = 'Identites et gouvernance'), 'Azure Policy', 'azure-policy-tags',
'Assigner une policy qui exige un tag sur les resource groups ou ressources.',
'Droits Resource Policy Contributor ou Owner sur le scope de test.',
'avance', 55, ARRAY['Azure Policy','Governance','Tags'],
'[{"label":"Lister definitions tag","command":"az policy definition list --query \"[?contains(displayName, ''tag'')].[displayName,name]\" -o table"},{"label":"Assigner policy","command":"az policy assignment create --name require-env-tag --display-name \"Require env tag\" --policy <definitionName> --params ''{\"tagName\":{\"value\":\"env\"}}'' --scope <scope>"}]'::jsonb,
ARRAY['Assigner au mauvais scope','Oublier que l evaluation n est pas instantanee','Confondre deny, audit et modify'],
ARRAY['Azure Policy evalue la conformite','Les effets changent le comportement de creation','Les initiatives regroupent plusieurs policies'],
ARRAY['L assignment est visible','Une ressource sans tag est audit ou refusee selon effet','Le compliance state apparait apres evaluation']),
((SELECT id FROM modules WHERE name = 'Identites et gouvernance'), 'Entra ID groups', 'entra-id-groups',
'Creer des groupes Entra ID et comprendre leur usage pour RBAC et administration.',
'Droits suffisants dans Entra ID, Azure CLI avec extension si necessaire.',
'debutant', 35, ARRAY['Microsoft Entra ID','Groups'],
'[{"label":"Creer groupe","command":"az ad group create --display-name az104-operators --mail-nickname az104-operators"},{"label":"Ajouter membre","command":"az ad group member add --group az104-operators --member-id <userObjectId>"}]'::jsonb,
ARRAY['Utiliser le display name quand l objectId est requis','Confondre groupe de securite et Microsoft 365 group','Ne pas attendre la replication dans RBAC'],
ARRAY['Les groupes simplifient les affectations RBAC','L objectId identifie vraiment le groupe','La gouvernance est meilleure avec groupes que comptes individuels'],
ARRAY['Le groupe existe','Le membre apparait dans la liste','Le groupe peut etre cible par une role assignment']),
((SELECT id FROM modules WHERE name = 'Securite et RBAC'), 'MFA et Conditional Access conceptuel', 'mfa-conditional-access-concepts',
'Construire un scenario Conditional Access sur papier et identifier les controles MFA adaptes.',
'Acces lecture a Entra ID, environnement de test recommande pour toute activation reelle.',
'debutant', 30, ARRAY['Conditional Access','MFA','Microsoft Entra ID'],
'[{"label":"Lister policies CA","command":"az rest --method GET --uri https://graph.microsoft.com/v1.0/identity/conditionalAccess/policies"},{"label":"Lire methodes auth","command":"az rest --method GET --uri https://graph.microsoft.com/v1.0/policies/authenticationMethodsPolicy"}]'::jsonb,
ARRAY['Activer une policy bloquante sans compte break-glass','Tester sur tous les utilisateurs en production','Confondre MFA per-user et Conditional Access moderne'],
ARRAY['Conditional Access combine signaux, conditions et controles','MFA reduit le risque de compromission de mot de passe','Les comptes break-glass doivent etre exclus et surveilles'],
ARRAY['Le scenario indique utilisateurs, apps, conditions et controles','Un compte break-glass est documente','Le mode report-only est choisi avant enforcement']),
((SELECT id FROM modules WHERE name = 'Stockage Azure'), 'Lifecycle management Blob', 'blob-lifecycle-management',
'Creer une regle de lifecycle management pour deplacer ou supprimer des blobs selon leur age.',
'Compte StorageV2 avec container blob et quelques fichiers de test.',
'intermediaire', 40, ARRAY['Blob Storage','Lifecycle Management'],
'[{"label":"Creer container","command":"az storage container create --account-name <storage> --name logs --auth-mode login"},{"label":"Appliquer policy","command":"az storage account management-policy create -g rg-az104-storage --account-name <storage> --policy @policy.json"}]'::jsonb,
ARRAY['Tester sur des donnees importantes','Oublier que les regles ne sont pas instantanees','Melanger hot/cool/archive sans comprendre les frais de rehydratation'],
ARRAY['Les tiers optimisent cout et disponibilite','Les policies s executent en arriere-plan','Archive est moins cher mais moins immediat'],
ARRAY['La policy est attachee au compte','Le JSON contient le bon prefix ou container','Les blobs eligibles changent de tier apres execution']),
((SELECT id FROM modules WHERE name = 'Machines virtuelles'), 'VM extensions et Custom Script', 'vm-custom-script-extension',
'Utiliser une extension VM pour installer un agent ou executer une configuration post-deploiement.',
'VM Linux ou Windows existante, script simple heberge ou inline.',
'avance', 50, ARRAY['Virtual Machines','VM Extensions'],
'[{"label":"Extension Linux","command":"az vm extension set -g rg-az104-vm --vm-name vm-az104-linux --name customScript --publisher Microsoft.Azure.Extensions --settings ''{\"commandToExecute\":\"sudo apt-get update && sudo apt-get install -y nginx\"}''"},{"label":"Voir extensions","command":"az vm extension list -g rg-az104-vm --vm-name vm-az104-linux -o table"}]'::jsonb,
ARRAY['Script non idempotent','Sortie d erreur non consultee','Extension bloquee par reseau ou package manager'],
ARRAY['Les extensions automatisent la configuration','Elles ont un etat de provisioning distinct de la VM','Un script doit pouvoir etre relance sans casser la VM'],
ARRAY['L extension est ProvisioningState/succeeded','Le service installe repond','Les logs extension ne montrent pas d erreur']);

INSERT INTO lab_steps (lab_id, step_order, title, instruction, command_hint) VALUES
((SELECT id FROM labs WHERE slug='resource-group-tags'),1,'Selectionner la subscription','Liste les subscriptions et selectionne celle reservee a tes labs pour eviter de creer des ressources au mauvais endroit.','az account list -o table && az account set --subscription <subscriptionId>'),
((SELECT id FROM labs WHERE slug='resource-group-tags'),2,'Creer le resource group','Cree le groupe de ressources avec une region coherente et les tags minimaux env, owner et costCenter.','az group create --name rg-az104-core --location canadacentral --tags env=lab owner=az104 costCenter=training'),
((SELECT id FROM labs WHERE slug='resource-group-tags'),3,'Verifier et corriger les tags','Affiche le groupe de ressources, verifie les tags, puis ajoute un tag purpose si besoin.','az group update --name rg-az104-core --set tags.purpose=practice'),
((SELECT id FROM labs WHERE slug='rbac-resource-group'),1,'Identifier le principal','Recupere l objectId du groupe ou utilisateur qui recevra le role.','az ad group show --group az104-operators --query id -o tsv'),
((SELECT id FROM labs WHERE slug='rbac-resource-group'),2,'Assigner le role minimal','Assigne Reader au scope du resource group, pas a la subscription.','az role assignment create --assignee <objectId> --role Reader --resource-group rg-az104-core'),
((SELECT id FROM labs WHERE slug='rbac-resource-group'),3,'Tester les limites','Connecte-toi ou simule le principal et confirme qu il peut lire mais pas modifier les ressources.','az role assignment list --resource-group rg-az104-core -o table'),
((SELECT id FROM labs WHERE slug='secure-storage-account'),1,'Preparer le nom','Choisis un nom unique de 3 a 24 caracteres en minuscules sans tirets.',''),
((SELECT id FROM labs WHERE slug='secure-storage-account'),2,'Creer le compte securise','Cree le compte avec HTTPS obligatoire et TLS 1.2 minimum.','az storage account create -g rg-az104-storage -n <uniquestorage> -l canadacentral --sku Standard_LRS --kind StorageV2 --https-only true --min-tls-version TLS1_2'),
((SELECT id FROM labs WHERE slug='secure-storage-account'),3,'Durcir l acces public','Desactive l acces public blob et verifie la configuration finale.','az storage account update -g rg-az104-storage -n <uniquestorage> --allow-blob-public-access false'),
((SELECT id FROM labs WHERE slug='azure-file-share'),1,'Creer le partage','Cree un share Azure Files avec quota limite pour le lab.','az storage share-rm create --resource-group rg-az104-storage --storage-account <uniquestorage> --name az104share --quota 5'),
((SELECT id FROM labs WHERE slug='azure-file-share'),2,'Ajouter un fichier test','Charge ou cree un petit fichier pour confirmer que le share est utilisable.','az storage file upload --account-name <uniquestorage> --share-name az104share --source .\\test.txt --path test.txt'),
((SELECT id FROM labs WHERE slug='azure-file-share'),3,'Verifier les limites reseau','Determine si ton reseau autorise SMB 445 ou si tu dois tester depuis Azure.','Test-NetConnection <storage>.file.core.windows.net -Port 445'),
((SELECT id FROM labs WHERE slug='windows-vm-basic'),1,'Creer la VM','Deploie Windows Server avec une taille economique pour le lab.','az vm create -g rg-az104-vm -n vm-az104-win --image Win2022Datacenter --admin-username azureadmin --admin-password <StrongPassword> --size Standard_B2s'),
((SELECT id FROM labs WHERE slug='windows-vm-basic'),2,'Limiter RDP','Ouvre RDP uniquement depuis ton IP publique actuelle.','az vm open-port -g rg-az104-vm -n vm-az104-win --port 3389 --source-address-prefixes <yourPublicIp>/32'),
((SELECT id FROM labs WHERE slug='windows-vm-basic'),3,'Valider l etat','Verifie l etat power/provisioning et recupere l IP publique.','az vm get-instance-view -g rg-az104-vm -n vm-az104-win --query instanceView.statuses'),
((SELECT id FROM labs WHERE slug='linux-vm-basic'),1,'Creer la VM','Deploie Ubuntu avec une cle SSH generee automatiquement.','az vm create -g rg-az104-vm -n vm-az104-linux --image Ubuntu2204 --admin-username azureuser --generate-ssh-keys --size Standard_B1s'),
((SELECT id FROM labs WHERE slug='linux-vm-basic'),2,'Installer un service','Connecte-toi en SSH et installe nginx pour avoir une verification simple.','sudo apt-get update && sudo apt-get install -y nginx'),
((SELECT id FROM labs WHERE slug='linux-vm-basic'),3,'Ouvrir HTTP','Autorise HTTP dans le NSG et teste depuis le navigateur.','az vm open-port -g rg-az104-vm -n vm-az104-linux --port 80'),
((SELECT id FROM labs WHERE slug='configure-nsg'),1,'Creer le NSG','Cree un NSG dedie au trafic web.','az network nsg create -g rg-az104-network -n nsg-az104-web'),
((SELECT id FROM labs WHERE slug='configure-nsg'),2,'Ajouter une regle','Ajoute une regle Allow HTTP avec une priorite explicite.','az network nsg rule create -g rg-az104-network --nsg-name nsg-az104-web -n Allow-HTTP --priority 200 --access Allow --protocol Tcp --direction Inbound --destination-port-ranges 80'),
((SELECT id FROM labs WHERE slug='configure-nsg'),3,'Associer et tester','Associe le NSG au subnet ou a la NIC puis teste le flux attendu.','az network vnet subnet update -g rg-az104-network --vnet-name vnet-az104 -n snet-web --network-security-group nsg-az104-web'),
((SELECT id FROM labs WHERE slug='vnet-subnet-basic'),1,'Dessiner le plan IP','Note l espace VNet et les subnets avant de creer les ressources.',''),
((SELECT id FROM labs WHERE slug='vnet-subnet-basic'),2,'Creer VNet et subnet web','Cree le VNet avec un premier subnet web.','az network vnet create -g rg-az104-network -n vnet-az104 -l canadacentral --address-prefix 10.10.0.0/16 --subnet-name snet-web --subnet-prefix 10.10.1.0/24'),
((SELECT id FROM labs WHERE slug='vnet-subnet-basic'),3,'Ajouter subnet data','Ajoute un deuxieme subnet reserve aux donnees.','az network vnet subnet create -g rg-az104-network --vnet-name vnet-az104 -n snet-data --address-prefixes 10.10.2.0/24'),
((SELECT id FROM labs WHERE slug='vnet-peering'),1,'Creer deux VNets','Cree vnet-a et vnet-b avec des CIDR non chevauchants.','az network vnet create -g rg-az104-network -n vnet-a --address-prefix 10.20.0.0/16 --subnet-name default --subnet-prefix 10.20.1.0/24'),
((SELECT id FROM labs WHERE slug='vnet-peering'),2,'Creer les peerings','Cree le peering dans les deux directions pour obtenir Connected.','az network vnet peering create -g rg-az104-network -n peer-a-to-b --vnet-name vnet-a --remote-vnet vnet-b --allow-vnet-access'),
((SELECT id FROM labs WHERE slug='vnet-peering'),3,'Tester la connectivite','Teste une connexion par IP privee entre deux VMs ou verifie les effective routes.','az network vnet peering list -g rg-az104-network --vnet-name vnet-a -o table'),
((SELECT id FROM labs WHERE slug='azure-bastion-basic'),1,'Creer le subnet Bastion','Ajoute AzureBastionSubnet avec un prefix /26 ou plus grand.','az network vnet subnet create -g rg-az104-network --vnet-name vnet-az104 -n AzureBastionSubnet --address-prefixes 10.10.250.0/26'),
((SELECT id FROM labs WHERE slug='azure-bastion-basic'),2,'Deployer Bastion','Cree l IP publique Standard puis la ressource Bastion.','az network bastion create -g rg-az104-network -n bastion-az104 --public-ip-address pip-bastion --vnet-name vnet-az104 --location canadacentral'),
((SELECT id FROM labs WHERE slug='azure-bastion-basic'),3,'Retirer l IP publique VM','Verifie que la VM peut etre administree sans IP publique directe.','az network nic ip-config update --ids <ipConfigId> --remove publicIpAddress'),
((SELECT id FROM labs WHERE slug='vm-backup-create'),1,'Creer le vault','Cree un Recovery Services Vault dans la meme region que la VM.','az backup vault create -g rg-az104-backup -n rsv-az104 -l canadacentral'),
((SELECT id FROM labs WHERE slug='vm-backup-create'),2,'Activer la protection','Attache la policy DefaultPolicy a la VM de test.','az backup protection enable-for-vm -g rg-az104-backup --vault-name rsv-az104 --vm vm-az104-linux --policy-name DefaultPolicy'),
((SELECT id FROM labs WHERE slug='vm-backup-create'),3,'Surveiller le job','Liste les jobs et confirme que la sauvegarde initiale demarre.','az backup job list -g rg-az104-backup --vault-name rsv-az104 -o table'),
((SELECT id FROM labs WHERE slug='vm-restore'),1,'Lister les items proteges','Trouve le container et l item de la VM sauvegardee.','az backup item list -g rg-az104-backup --vault-name rsv-az104 --backup-management-type AzureIaasVM --workload-type VM -o table'),
((SELECT id FROM labs WHERE slug='vm-restore'),2,'Choisir un point','Liste les recovery points et choisis le plus recent valide.','az backup recoverypoint list -g rg-az104-backup --vault-name rsv-az104 --container-name <container> --item-name <item> --backup-management-type AzureIaasVM --workload-type VM'),
((SELECT id FROM labs WHERE slug='vm-restore'),3,'Restaurer les disques','Lance une restauration de disques dans un RG de test et suis le job.','az backup restore restore-disks -g rg-az104-backup --vault-name rsv-az104 --container-name <container> --item-name <item> --rp-name <rpName> --storage-account <storage>'),
((SELECT id FROM labs WHERE slug='azure-monitor-alert'),1,'Creer action group','Cree un groupe d action avec un email que tu peux confirmer.','az monitor action-group create -g rg-az104-monitor -n ag-az104 --short-name az104 --action email admin az104@example.com'),
((SELECT id FROM labs WHERE slug='azure-monitor-alert'),2,'Creer alerte metrique','Cree une alerte CPU sur la VM avec seuil de test.','az monitor metrics alert create -g rg-az104-monitor -n vm-cpu-high --scopes <vmResourceId> --condition "avg Percentage CPU > 80" --window-size 5m --evaluation-frequency 1m --action ag-az104'),
((SELECT id FROM labs WHERE slug='azure-monitor-alert'),3,'Declencher ou simuler','Genere de la charge ou abaisse temporairement le seuil pour observer l etat.','az monitor metrics alert show -g rg-az104-monitor -n vm-cpu-high'),
((SELECT id FROM labs WHERE slug='log-analytics-workspace'),1,'Creer workspace','Cree un workspace Log Analytics pour les labs monitoring.','az monitor log-analytics workspace create -g rg-az104-monitor -n law-az104 -l canadacentral'),
((SELECT id FROM labs WHERE slug='log-analytics-workspace'),2,'Noter les identifiants','Recupere customerId et resourceId pour les diagnostics.','az monitor log-analytics workspace show -g rg-az104-monitor -n law-az104'),
((SELECT id FROM labs WHERE slug='log-analytics-workspace'),3,'Executer une requete','Teste une requete KQL simple une fois des donnees envoyees.','az monitor log-analytics query -w <workspaceId> --analytics-query "AzureActivity | take 5"'),
((SELECT id FROM labs WHERE slug='diagnostic-settings'),1,'Identifier la ressource','Recupere le resourceId de la ressource a surveiller et celui du workspace.','az resource show -g <rg> -n <name> --resource-type <type> --query id -o tsv'),
((SELECT id FROM labs WHERE slug='diagnostic-settings'),2,'Creer le setting','Active logs et metriques disponibles vers Log Analytics.','az monitor diagnostic-settings create --name diag-az104 --resource <resourceId> --workspace <workspaceResourceId> --metrics "[{category:AllMetrics,enabled:true}]"'),
((SELECT id FROM labs WHERE slug='diagnostic-settings'),3,'Verifier ingestion','Attends quelques minutes puis confirme que les tables recoivent des donnees.','az monitor diagnostic-settings list --resource <resourceId>'),
((SELECT id FROM labs WHERE slug='managed-identity'),1,'Activer identity','Active une system-assigned managed identity sur la VM.','az vm identity assign -g rg-az104-vm -n vm-az104-linux'),
((SELECT id FROM labs WHERE slug='managed-identity'),2,'Donner un role','Assigne un role minimal a l identity sur la ressource cible.','az role assignment create --assignee <principalId> --role "Storage Blob Data Reader" --scope <storageResourceId>'),
((SELECT id FROM labs WHERE slug='managed-identity'),3,'Tester depuis la VM','Depuis la VM, demande un token a IMDS et teste l acces.','curl -H Metadata:true "http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://storage.azure.com/"'),
((SELECT id FROM labs WHERE slug='key-vault-basics'),1,'Creer le vault','Cree un Key Vault en mode RBAC.','az keyvault create -g rg-az104-sec -n <uniqueVaultName> -l canadacentral --enable-rbac-authorization true'),
((SELECT id FROM labs WHERE slug='key-vault-basics'),2,'Ajouter un secret','Stocke un secret de demo non sensible.','az keyvault secret set --vault-name <uniqueVaultName> -n demo-secret --value "ChangeMe123!"'),
((SELECT id FROM labs WHERE slug='key-vault-basics'),3,'Tester l acces','Lis le secret avec un principal autorise, puis observe le refus avec un principal non autorise.','az keyvault secret show --vault-name <uniqueVaultName> -n demo-secret'),
((SELECT id FROM labs WHERE slug='azure-policy-tags'),1,'Choisir la definition','Trouve une definition built-in liee aux tags.','az policy definition list --query "[?contains(displayName, ''tag'')].[displayName,name]" -o table'),
((SELECT id FROM labs WHERE slug='azure-policy-tags'),2,'Assigner au scope de test','Assigne la policy au RG ou a la subscription de lab.','az policy assignment create --name require-env-tag --policy <definitionName> --scope <scope>'),
((SELECT id FROM labs WHERE slug='azure-policy-tags'),3,'Tester la conformite','Cree une ressource avec et sans tag pour comprendre l effet.','az policy state list --resource-group rg-az104-core -o table'),
((SELECT id FROM labs WHERE slug='entra-id-groups'),1,'Creer le groupe','Cree un groupe de securite pour les operateurs AZ-104.','az ad group create --display-name az104-operators --mail-nickname az104-operators'),
((SELECT id FROM labs WHERE slug='entra-id-groups'),2,'Ajouter un membre','Ajoute un utilisateur test via son objectId.','az ad group member add --group az104-operators --member-id <userObjectId>'),
((SELECT id FROM labs WHERE slug='entra-id-groups'),3,'Utiliser le groupe','Utilise le groupe dans une affectation RBAC de lab.','az role assignment create --assignee <groupObjectId> --role Reader --resource-group rg-az104-core'),
((SELECT id FROM labs WHERE slug='mfa-conditional-access-concepts'),1,'Definir le scenario','Ecris qui est cible, quelles apps sont protegees, et quels risques declenchent MFA.',''),
((SELECT id FROM labs WHERE slug='mfa-conditional-access-concepts'),2,'Prevoir les exclusions','Documente le compte break-glass, les exclusions et la surveillance associee.',''),
((SELECT id FROM labs WHERE slug='mfa-conditional-access-concepts'),3,'Valider en report-only','Explique comment tu testerais la policy en report-only avant enforcement.','az rest --method GET --uri https://graph.microsoft.com/v1.0/identity/conditionalAccess/policies'),
((SELECT id FROM labs WHERE slug='blob-lifecycle-management'),1,'Creer des blobs test','Cree un container logs et charge quelques fichiers de test.','az storage container create --account-name <storage> --name logs --auth-mode login'),
((SELECT id FROM labs WHERE slug='blob-lifecycle-management'),2,'Rediger policy JSON','Prepare une regle qui deplace les blobs logs vers cool apres quelques jours.',''),
((SELECT id FROM labs WHERE slug='blob-lifecycle-management'),3,'Appliquer et verifier','Applique la policy et relis-la depuis Azure.','az storage account management-policy show -g rg-az104-storage --account-name <storage>'),
((SELECT id FROM labs WHERE slug='vm-custom-script-extension'),1,'Preparer le script','Rends le script idempotent: il peut etre relance sans erreur bloquante.',''),
((SELECT id FROM labs WHERE slug='vm-custom-script-extension'),2,'Executer l extension','Lance Custom Script Extension sur la VM cible.','az vm extension set -g rg-az104-vm --vm-name vm-az104-linux --name customScript --publisher Microsoft.Azure.Extensions --settings ''{"commandToExecute":"sudo apt-get update && sudo apt-get install -y nginx"}'''),
((SELECT id FROM labs WHERE slug='vm-custom-script-extension'),3,'Lire le resultat','Verifie le provisioning state et les logs extension si necessaire.','az vm extension show -g rg-az104-vm --vm-name vm-az104-linux -n customScript');

INSERT INTO user_lab_progress (lab_id, status, completed_step_ids, personal_notes)
SELECT id,
  CASE WHEN slug IN ('resource-group-tags','linux-vm-basic','azure-monitor-alert') THEN 'in_progress' ELSE 'not_started' END,
  CASE
    WHEN slug = 'resource-group-tags' THEN ARRAY[(SELECT id FROM lab_steps WHERE lab_id = labs.id AND step_order = 1)]
    WHEN slug = 'linux-vm-basic' THEN ARRAY[(SELECT id FROM lab_steps WHERE lab_id = labs.id AND step_order = 1)]
    WHEN slug = 'azure-monitor-alert' THEN ARRAY[(SELECT id FROM lab_steps WHERE lab_id = labs.id AND step_order = 1)]
    ELSE ARRAY[]::INTEGER[]
  END,
  CASE WHEN slug = 'resource-group-tags' THEN 'Penser a standardiser les tags avant les prochains labs.' ELSE '' END
FROM labs;

INSERT INTO quiz_questions (module_id, question, choices, correct_answer, explanation, difficulty) VALUES
((SELECT id FROM modules WHERE name = 'Identites et gouvernance'), 'Quel scope RBAC est le plus restrictif pour donner acces a une equipe sur un seul groupe de ressources ?', '["Subscription","Management group","Resource group","Tenant root group"]', 2, 'Le scope resource group limite les permissions aux ressources contenues dans ce groupe.', 'debutant'),
((SELECT id FROM modules WHERE name = 'Stockage Azure'), 'Quel container est utilise par le site web statique d''un compte de stockage ?', '["$root","$logs","$web","static"]', 2, 'Azure Storage utilise le container special $web pour le contenu statique.', 'intermediaire'),
((SELECT id FROM modules WHERE name = 'Machines virtuelles'), 'Quel mecanisme injecte une configuration au premier demarrage d''une VM Linux ?', '["cloud-init","Azure Policy","Managed Identity","VNet peering"]', 0, 'cloud-init execute une configuration initiale pendant le provisioning Linux.', 'intermediaire'),
((SELECT id FROM modules WHERE name = 'Reseau virtuel'), 'Quel composant filtre le trafic reseau au niveau subnet ou NIC ?', '["NSG","Route table uniquement","Recovery vault","Log Analytics workspace"]', 0, 'Un Network Security Group applique des regles entrantes et sortantes.', 'debutant'),
((SELECT id FROM modules WHERE name = 'Monitoring'), 'Ou stocke-t-on les requetes KQL et journaux collectes pour analyse ?', '["Log Analytics workspace","Storage queue","Azure Files","Key Vault"]', 0, 'Log Analytics centralise les logs Azure Monitor et permet les requetes KQL.', 'intermediaire'),
((SELECT id FROM modules WHERE name = 'Backup et Recovery'), 'Quel service protege les workloads par politiques de sauvegarde ?', '["Azure Backup","Azure Front Door","Azure Bastion","Azure Firewall"]', 0, 'Azure Backup utilise des vaults et politiques pour proteger les workloads.', 'debutant'),
((SELECT id FROM modules WHERE name = 'Securite et RBAC'), 'Quel principe recommande d''attribuer uniquement les permissions necessaires ?', '["Defense in depth","Least privilege","Hot path","Eventual consistency"]', 1, 'Le least privilege reduit la surface de risque en limitant les droits.', 'debutant');

INSERT INTO notes (module_id, title, content, tags) VALUES
((SELECT id FROM modules WHERE name = 'Securite et RBAC'), 'RBAC scopes', 'Ordre des scopes: management group > subscription > resource group > resource. Toujours choisir le scope le plus bas possible.', ARRAY['rbac','gouvernance']),
((SELECT id FROM modules WHERE name = 'Machines virtuelles'), 'Commandes VM utiles', 'az vm list-ip-addresses -g <rg> -n <vm> -o table\naz vm get-instance-view -g <rg> -n <vm> --query instanceView.statuses', ARRAY['vm','cli']),
((SELECT id FROM modules WHERE name = 'Monitoring'), 'KQL depart rapide', 'AzureActivity | summarize count() by OperationNameValue | order by count_ desc', ARRAY['monitoring','kql']);

INSERT INTO resources (module_id, title, url, resource_type, content) VALUES
((SELECT id FROM modules WHERE name = 'Securite et RBAC'), 'Docs Azure RBAC', 'https://learn.microsoft.com/azure/role-based-access-control/overview', 'doc', 'Vue d''ensemble RBAC officielle.'),
((SELECT id FROM modules WHERE name = 'Stockage Azure'), 'Static website hosting', 'https://learn.microsoft.com/azure/storage/blobs/storage-blob-static-website', 'doc', 'Guide Microsoft Learn pour heberger un site statique.'),
((SELECT id FROM modules WHERE name = 'Machines virtuelles'), 'Azure CLI VM cheat sheet', NULL, 'commande', 'az vm create\naz vm open-port\naz vm extension set'),
((SELECT id FROM modules WHERE name = 'Monitoring'), 'KQL quick reference', 'https://learn.microsoft.com/azure/data-explorer/kql-quick-reference', 'reference', 'Reference rapide KQL.'),
((SELECT id FROM modules WHERE name = 'Securite et RBAC'), 'Defender for Cloud recommendations', 'https://learn.microsoft.com/azure/defender-for-cloud/recommendations-reference', 'reference', 'Catalogue de recommandations securite.');
